In [22]:
!pip install -U sentence-transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 85 kB 2.9 MB/s 
     |████████████████████████████████| 5.5 MB 27.9 MB/s 
     |████████████████████████████████| 1.3 MB 54.8 MB/s 
     |████████████████████████████████| 182 kB 60.7 MB/s 
     |████████████████████████████████| 7.6 MB 43.0 MB/s 
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125938 sha256=2226ce9ac77a37aafd699424bf651b5831fecc325269d0ef4b0b60354af1efa9
  Stored in directory: /root/.cache/pip/wheels/bf/06/fb/d59c1e5bd1dac7f6cf61ec0036cc3a10ab8fecaa6b2c3d3ee9
Successfully built sentence-transformers


In [17]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
cd drive/MyDrive/REFSQ/SBERT

/content/drive/MyDrive/REFSQ/SBERT


In [3]:
import pandas as pd

In [26]:
dfNew = pd.read_excel (r'dfNew.xlsx')

In [ ]:
 print(dfNew['Name']+dfNew['Description'] )

0      Improper Neutralization of Input During Web Pa...
1      Use of a Broken or Risky Cryptographic Algorit...
2      Use of a Broken or Risky Cryptographic Algorit...
3      Deserialization of Untrusted DataThe applicati...
4      Deserialization of Untrusted DataThe applicati...
                             ...                        
604    Improper Neutralization of Special Elements in...
605    Improper Neutralization of Special Elements in...
606    Improper Neutralization of Special Elements in...
607    Improper Limitation of a Pathname to a Restric...
608    Improper Restriction of XML External Entity Re...
Length: 609, dtype: object


In [ ]:
dfNew

In [19]:
dfDesc = pd.read_excel (r'dfDesc.xlsx')

In [ ]:
dfDesc

Desc
0    fix: Verify a given 'mimeType' and/or 'callbac...
1                    BJA-694 cleaned up primality test
2                    BJA-694 cleaned up primality test
3    added additional checking to XMSS BDS tree par...
4    added additional checking to XMSS BDS tree par...
..                                                 ...
604                                          "2.67v"\n
605                      "adding body_pos docstring"\n
606  "rename onig_get_tag_start/end() to onig_get_c...
607     ":pencil: Update common web attack resource"\n
608  "Run mypy during build checks and start adding...

[609 rows x 1 columns]

In [20]:
Desc = list(dfDesc['Desc'])

In [ ]:
Desc[0]

"fix: Verify a given 'mimeType' and/or 'callback' request parameter\n\nSo that only fixed values are possible, in order to avoid XSS attack\nvectors."

In [24]:
from sentence_transformers import SentenceTransformer,util
model = SentenceTransformer('all-MiniLM-L6-v2')

Downloading:   0%|          | 0.00/1.18k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/612 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/116 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/39.3k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/350 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/13.2k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/349 [00:00<?, ?B/s]

In [ ]:
for i in range (len(Desc)):
   Desc[i] = str(Desc[i])

In [ ]:
Desc[0]

In [27]:
# Two lists of sentences
# sentences1 = ['The cat sits outside',
#               'The cat sits inside',
#               'The new movie is so great']

sentences1 = dfNew['BadCode']
#sentences1 = Desc
#print(sentences1)

# sentences2 = ['The cat sits outside',
#               'The cat sits inside',
#               'The new movie is so great']

#Compute embedding for both lists

embeddings1 = model.encode(sentences1, convert_to_tensor=True)

# embeddings2 = model.encode(sentences2, convert_to_tensor=True)

#Compute cosine-similarities
cosine_scores = util.cos_sim(embeddings1, embeddings1)
npArr = cosine_scores.detach().numpy()
print(npArr)

#Output the pairs with their score
# for i in range(len(sentences1-1)):
#     print("{} \t\t {} \t\t Score: {:.4f}".format(sentences1[i], sentences1[i+], cosine_scores[i][j]))
  

[[1.0000002  0.1740991  0.13423559 ... 0.24847825 0.19883357 0.21446717]
 [0.1740991  0.99999994 0.25516313 ... 0.21123172 0.17242329 0.10133958]
 [0.13423559 0.25516313 1.0000004  ... 0.10805664 0.12334701 0.03456639]
 ...
 [0.2484782  0.2112318  0.10805668 ... 1.         0.04218888 0.16751406]
 [0.19883355 0.17242329 0.12334706 ... 0.04218888 0.9999999  0.18003988]
 [0.21446717 0.10133958 0.03456639 ... 0.16751407 0.18003988 1.        ]]


In [28]:
f= open('outputEmbedding.txt','w')
for i in range(len(npArr)):
  for j in range(len(npArr)):
    f.write(str(npArr[i][j])+" ")
  f.write("\n")
f.close()

In [29]:
import pandas as pd
  
# read text file into pandas DataFrame
df = pd.read_csv("outputEmbedding.txt",  sep=' ', header = None)
  
# display DataFrame
print(df.shape)

(609, 610)


In [ ]:
df

In [30]:
df.drop(df.columns[[609]], axis=1, inplace=True)

In [31]:
listBadGood = list()
for i in range(0,201):
  listBadGood.append("Bad")

for i in range(0,408):
  listBadGood.append("Good")
print(len(listBadGood))

609


In [32]:
listIndex = list()
for i in range(0,609):
  listIndex.append(i)

In [33]:
df['GroundTruth'] = listBadGood
df['Index'] = listIndex

In [ ]:
f = open("topResult.txt","w")
ls = df.values.tolist()
lenOfData = 609

for j in range(0,lenOfData):
  #print(j)
  #print(ls[j])
  temp = list()
  for i in range(0,lenOfData):
    temp.append(ls[j][i])
  temp3= temp
  res = sorted(range(len(temp)), key = lambda sub: temp[sub])[-6:]
  
  #print("Indices list of max N elements is : " + str(res))
  if (j) in res:
    res.remove(j)
  else:
    #print("here")
    res = sorted(range(len(temp)), key = lambda sub: temp[sub])[-5:]
  #print(res)
  #item = ls[0][894]
  #print(item)
  #res.remove(item)
  #print("Indices list of max N elements is : " + str(res))
  temp2 = list()
  f.write(str(ls[j][lenOfData+1])+" "+str(ls[j][lenOfData])+" ")
  temp3 = list()
  for i in range(0,len(res)):
    temp4 = list()
    #print(temp[res[i]])
    #print(res[i])
    temp4.append(temp[res[i]])
    temp4.append(res[i])
    temp3.append(temp4)
  new_data = sorted(temp3, key=lambda row: (row[0]), reverse=True)
  #print("sorted")
  #print(new_data)
  res2=list()
  for i in range(0,len(new_data)):
    #print(new_data[i][1])
    res2.append(new_data[i][1])
  #print("res2")
  #print(res2)
  for i in range(0,len(res2)):
    '''
    print(ls[j][894])
    print(ls[j][893])
    print(temp[res[i]])
    print(res[i])
    print(ls[res[i]][893])
    '''
    f.write(str(temp[res2[i]])+" "+str(res2[i])+" "+str(ls[res2[i]][lenOfData])+" ")
    temp2.append(ls[res2[i]][lenOfData])
    #print(temp3)
  #print(temp2)
  badCount = temp2.count('Bad')
  goodCount = temp2.count('Good')
  f.write(str(badCount)+" "+ str(goodCount) +" ")
  resultFound = str()
  if badCount>goodCount:
    resultFound = 'Bad'
  else:
    resultFound ="Good"
  f.write(str(resultFound))
  f.write("\n")
#print(temp2)

f.close()

In [ ]:
# n = 3

In [34]:
f = open("topResult.txt","w")
ls = df.values.tolist()
lenOfData = 609

for j in range(0,lenOfData):
  #print(j)
  #print(ls[j])
  temp = list()
  for i in range(0,lenOfData):
    temp.append(ls[j][i])
  temp3= temp
  res = sorted(range(len(temp)), key = lambda sub: temp[sub])[-4:]
  
  #print("Indices list of max N elements is : " + str(res))
  if (j) in res:
    res.remove(j)
  else:
    #print("here")
    res = sorted(range(len(temp)), key = lambda sub: temp[sub])[-3:]
  #print(res)
  #item = ls[0][894]
  #print(item)
  #res.remove(item)
  #print("Indices list of max N elements is : " + str(res))
  temp2 = list()
  f.write(str(ls[j][lenOfData+1])+" "+str(ls[j][lenOfData])+" ")
  temp3 = list()
  for i in range(0,len(res)):
    temp4 = list()
    #print(temp[res[i]])
    #print(res[i])
    temp4.append(temp[res[i]])
    temp4.append(res[i])
    temp3.append(temp4)
  new_data = sorted(temp3, key=lambda row: (row[0]), reverse=True)
  #print("sorted")
  #print(new_data)
  res2=list()
  for i in range(0,len(new_data)):
    #print(new_data[i][1])
    res2.append(new_data[i][1])
  #print("res2")
  #print(res2)
  for i in range(0,len(res2)):
    '''
    print(ls[j][894])
    print(ls[j][893])
    print(temp[res[i]])
    print(res[i])
    print(ls[res[i]][893])
    '''
    f.write(str(temp[res2[i]])+" "+str(res2[i])+" "+str(ls[res2[i]][lenOfData])+" ")
    temp2.append(ls[res2[i]][lenOfData])
    #print(temp3)
  #print(temp2)
  badCount = temp2.count('Bad')
  goodCount = temp2.count('Good')
  f.write(str(badCount)+" "+ str(goodCount) +" ")
  resultFound = str()
  if badCount>goodCount:
    resultFound = 'Bad'
  else:
    resultFound ="Good"
  f.write(str(resultFound))
  f.write("\n")
#print(temp2)

f.close()

In [35]:
# read text file into pandas DataFrame
df3 = pd.read_csv("topResult.txt", sep=" ", header=None)
  
# display DataFrame
print(df3.shape)

(609, 14)


In [36]:
listGood =list()
listBad = list()

for i in range(0,609):
  bad =0
  good =0
  tList= df3.iloc[i].tolist()
  print(tList)
  if tList[4] == 'Bad':
    bad += 5*tList[2]
  else:
    good += 5*tList[2]

  if tList[7] == 'Bad':
    bad += 4*tList[5]
  else:
    good += 4*tList[5]

  if tList[10] == 'Bad':
    bad += 3*tList[8]
  else:
    good += 3*tList[8]
  
  # if tList[13] == 'Bad':
  #   bad += 2*tList[11]
  # else:
  #   good += 2*tList[11]

  # if tList[16] == 'Bad':
  #   bad += 1*tList[14]
  # else:
  #   good += 1*tList[14]
  
  listGood.append(good)
  listBad.append(bad)
  print(good)
  print(bad)


[0, 'Bad', 0.51581883, 359, 'Good', 0.50968885, 280, 'Good', 0.5025203, 74, 'Bad', 1, 2, 'Good']
4.617849549999999
1.5075609
[1, 'Bad', 0.42271426, 448, 'Good', 0.38834423, 366, 'Good', 0.38501316, 536, 'Good', 0, 3, 'Good']
4.8219877
0
[2, 'Bad', 0.9625839, 203, 'Good', 0.36591282, 410, 'Good', 0.35748905, 390, 'Good', 0, 3, 'Good']
7.34903793
0
[3, 'Bad', 0.97574854, 204, 'Good', 0.38717324, 355, 'Good', 0.36468172, 356, 'Good', 0, 3, 'Good']
7.521480820000001
0
[4, 'Bad', 0.99062663, 205, 'Good', 0.49740434, 423, 'Good', 0.46610823, 366, 'Good', 0, 3, 'Good']
8.341075199999999
0
[5, 'Bad', 0.9300424, 206, 'Good', 0.8338593, 320, 'Good', 0.75946724, 254, 'Good', 0, 3, 'Good']
10.264050919999999
0
[6, 'Bad', 0.9570581, 210, 'Good', 0.5480717, 209, 'Good', 0.49211788, 211, 'Good', 0, 3, 'Good']
8.45393094
0
[7, 'Bad', 0.92691505, 211, 'Good', 0.61744195, 329, 'Good', 0.5724056, 328, 'Good', 0, 3, 'Good']
8.82155985
0
[8, 'Bad', 0.8752724, 235, 'Good', 0.6523468, 94, 'Bad', 0.6332128, 3

In [ ]:
df3[20]=listGood
df3[21] = listBad

In [37]:
df3[14]=listGood
df3[15] = listBad

In [ ]:
df3

In [38]:
df3.to_excel("result.xlsx")